import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Musicopileai</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-[#FF0000] to-[#0072C6]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Musico<span className="text-[#87CEEB]">phileai</span>
          </h1>
          <h4 className="text-3xl font-bold text-slate-300" >Finding good songs can be challenging, don&apos;t you think?</h4>
          <div>
            <Link href={"/recommendation"} className="px-8 py-5 rounded-full bg-gray-900 flex justify-center" >
              <span className="text-3xl text-[#87CEEB] font-bold" >Get Started</span>
            </Link>
          </div>
          <p className="text-2xl text-white">
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
